"""添加通用爬虫引擎所需字段

Revision ID: ee88b6d87c4e
Revises: 
Create Date: 2026-01-07 21:09:39.493565

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee88b6d87c4e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('crawler_config', schema=None) as batch_op:
        batch_op.add_column(sa.Column('headers', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('request_params', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('request_method', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('parse_rules', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('timeout', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('retry_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('proxy', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('crawler_config', schema=None) as batch_op:
        batch_op.drop_column('proxy')
        batch_op.drop_column('retry_count')
        batch_op.drop_column('timeout')
        batch_op.drop_column('parse_rules')
        batch_op.drop_column('request_method')
        batch_op.drop_column('request_params')
        batch_op.drop_column('headers')

    # ### end Alembic commands ###
